# Copyright (c) 2017 Dustin Doloff
# Licensed under Apache License v2.0

load(":actions_test.bzl", "run_all_tests")

run_all_tests()

load(":collections_test.bzl", "run_all_tests")

run_all_tests()

load(":control_flow_test.bzl", "run_all_tests")

run_all_tests()

load(":rules_test.bzl", "run_all_tests")

run_all_tests()
