# Copyright (c) 2017 Dustin Doloff
# Licensed under Apache License v2.0

py_binary(
    name = "assert_equal",
    srcs = [
        "scripts/assert_equal.py",
    ],
    visibility = [ "//visibility:public" ],
)
